# Site settings
title: On the streets / Saving the scene / from the forces of / Evil
name: On the streets / Saving the scene / from the forces of / Evil
url: "http://ghoulmann.github.io"
email: rikgoldman@gmail.com
description: Testing gh-pages
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: 9_while_9
github_username:  ghoulmann
rss_url: "/feed.xml"
logo_image: ""
# Build settings
gems: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
